#!/bin/bash

# Automaker Profile Switcher
# Quickly switch between ~/.ccs profiles and start the server

set -e

CCS_DIR="$HOME/.ccs"
AUTOMAKER_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$AUTOMAKER_DIR/.env"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Get list of profiles
get_profiles() {
    ls "$CCS_DIR"/*.settings.json 2>/dev/null | xargs -n1 basename | sed 's/.settings.json$//'
}

# Show current profile
show_current() {
    if [[ -f "$ENV_FILE" ]]; then
        local base_url=$(grep "^ANTHROPIC_BASE_URL=" "$ENV_FILE" | cut -d'=' -f2-)
        local model=$(grep "^ANTHROPIC_MODEL=" "$ENV_FILE" | cut -d'=' -f2-)
        echo -e "${CYAN}Current config:${NC}"
        echo -e "  BASE_URL: ${YELLOW}$base_url${NC}"
        echo -e "  MODEL: ${YELLOW}$model${NC}"
    fi
}

# Show menu
show_menu() {
    echo -e "\n${BLUE}╔════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║    Automaker Profile Switcher          ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════╝${NC}\n"

    show_current

    echo -e "\n${GREEN}Available profiles:${NC}\n"

    local i=1
    for profile in $(get_profiles); do
        local settings_file="$CCS_DIR/$profile.settings.json"
        local base_url=$(jq -r '.env.ANTHROPIC_BASE_URL // "N/A"' "$settings_file" 2>/dev/null)
        local model=$(jq -r '.env.ANTHROPIC_MODEL // "N/A"' "$settings_file" 2>/dev/null)

        # Extract domain from URL for cleaner display
        local domain=$(echo "$base_url" | sed -E 's|https?://([^/]+).*|\1|')

        printf "  ${YELLOW}%d)${NC} %-8s ${CYAN}%-30s${NC} %s\n" "$i" "$profile" "$domain" "$model"
        ((i++))
    done

    echo ""
    echo -e "  ${YELLOW}s)${NC} Start server + UI (full stack)"
    echo -e "  ${YELLOW}r)${NC} Restart server + UI"
    echo -e "  ${YELLOW}k)${NC} Stop server + UI"
    echo -e "  ${YELLOW}q)${NC} Quit"
    echo ""
}

# Apply profile to .env
apply_profile() {
    local profile=$1
    local settings_file="$CCS_DIR/$profile.settings.json"

    if [[ ! -f "$settings_file" ]]; then
        echo -e "${RED}Error: Profile '$profile' not found${NC}"
        return 1
    fi

    echo -e "${CYAN}Applying profile: $profile${NC}"

    # Read env vars from settings file
    local env_vars=$(jq -r '.env | to_entries | .[] | "\(.key)=\(.value)"' "$settings_file" 2>/dev/null)

    # Create new .env file
    cat > "$ENV_FILE" << 'HEADER'
# ====== PROXY CONFIGURATION ======
# Auto-generated by switch-profile.sh
# Profile: PROFILE_NAME
HEADER

    # Replace placeholder with actual profile name
    sed -i '' "s/PROFILE_NAME/$profile/" "$ENV_FILE"

    # Add env vars from profile
    echo "$env_vars" >> "$ENV_FILE"

    # Also set ANTHROPIC_API_KEY to same as AUTH_TOKEN if not set
    if ! grep -q "^ANTHROPIC_API_KEY=" "$ENV_FILE"; then
        local auth_token=$(jq -r '.env.ANTHROPIC_AUTH_TOKEN // ""' "$settings_file")
        if [[ -n "$auth_token" ]]; then
            echo "ANTHROPIC_API_KEY=$auth_token" >> "$ENV_FILE"
        fi
    fi

    # Add static config
    cat >> "$ENV_FILE" << 'FOOTER'

# ====== GITHUB & SYSTEM ======
GH_TOKEN=${GH_TOKEN:-}
ALLOWED_ROOT_DIRECTORY=/Users/mac/tools

# Fixed API Key for login
AUTOMAKER_API_KEY=admin123
FOOTER

    echo -e "${GREEN}✓ Profile '$profile' applied to .env${NC}"
}

# Stop server and UI
stop_all() {
    echo -e "${YELLOW}Stopping server and UI...${NC}"
    pkill -f "tsx watch.*automaker" 2>/dev/null || true
    pkill -f "node.*automaker.*3008" 2>/dev/null || true
    pkill -f "vite.*3007" 2>/dev/null || true
    pkill -f "vite" 2>/dev/null || true
    sleep 1
    echo -e "${GREEN}✓ Server and UI stopped${NC}"
}

# Start full stack (UI + server)
start_full() {
    echo -e "${CYAN}Starting server and UI...${NC}"
    cd "$AUTOMAKER_DIR"
    # Start both without rebuilding packages (faster)
    npm run _dev:server &>/dev/null &
    npm run _dev:web &>/dev/null &

    # Wait for both to be ready
    echo -n "Waiting for services"
    for i in {1..30}; do
        local server_ok=$(curl -s http://localhost:3008/api/health > /dev/null 2>&1 && echo "1")
        local ui_ok=$(curl -s http://localhost:3007 > /dev/null 2>&1 && echo "1")
        if [[ "$server_ok" == "1" && "$ui_ok" == "1" ]]; then
            echo ""
            echo -e "${GREEN}✓ Server ready at http://localhost:3008${NC}"
            echo -e "${GREEN}✓ UI ready at http://localhost:3007${NC}"
            return 0
        fi
        echo -n "."
        sleep 1
    done
    echo ""
    echo -e "${YELLOW}Services are starting in background...${NC}"
}

# Main
main() {
    # Check dependencies
    if ! command -v jq &> /dev/null; then
        echo -e "${RED}Error: jq is required. Install with: brew install jq${NC}"
        exit 1
    fi

    # Quick mode: pass profile name as argument
    if [[ -n "$1" ]]; then
        case "$1" in
            -s|--start)
                start_full
                exit 0
                ;;
            -k|--stop)
                stop_all
                exit 0
                ;;
            -r|--restart)
                stop_all
                start_full
                exit 0
                ;;
            -f|--full)
                start_full
                exit 0
                ;;
            -h|--help)
                echo "Usage: $0 [profile|option]"
                echo ""
                echo "Profiles: $(get_profiles | tr '\n' ' ')"
                echo ""
                echo "Options:"
                echo "  -s, --start    Start server + UI (default)"
                echo "  -k, --stop     Stop server + UI"
                echo "  -r, --restart  Restart server + UI"
                echo "  -f, --full     Start full stack (same as -s)"
                echo "  -h, --help     Show this help"
                exit 0
                ;;
            *)
                # Treat as profile name
                if [[ -f "$CCS_DIR/$1.settings.json" ]]; then
                    apply_profile "$1"
                    stop_all
                    start_full
                    exit 0
                else
                    echo -e "${RED}Unknown profile: $1${NC}"
                    exit 1
                fi
                ;;
        esac
    fi

    # Interactive mode
    while true; do
        show_menu
        read -p "Select option: " choice

        case "$choice" in
            [1-9]|[1-9][0-9])
                local profiles=($(get_profiles))
                local idx=$((choice - 1))
                if [[ $idx -ge 0 && $idx -lt ${#profiles[@]} ]]; then
                    apply_profile "${profiles[$idx]}"
                    read -p "Start services? [Y/n]: " start_choice
                    if [[ "$start_choice" != "n" && "$start_choice" != "N" ]]; then
                        stop_all
                        start_full
                    fi
                else
                    echo -e "${RED}Invalid choice${NC}"
                fi
                ;;
            s|S)
                start_full
                ;;
            r|R)
                stop_all
                start_full
                ;;
            k|K)
                stop_all
                ;;
            q|Q)
                echo "Bye!"
                exit 0
                ;;
            *)
                echo -e "${RED}Invalid choice${NC}"
                ;;
        esac

        read -p "Press Enter to continue..."
    done
}

main "$@"
